// Stamps src/version.js with the current git commit hash (short).
// Usage: node tools/write_version.js [outfile]   (default: src/version.js)
// Falls back to 'dev' when git is unavailable. The dev server overrides this with 'dev' anyway.
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const out = path.resolve(process.argv[2] || path.join(__dirname, '..', 'src', 'version.js'));
let v = 'dev';
try {
  v = execSync('git rev-parse --short=7 HEAD', { cwd: path.join(__dirname, '..'), stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim() || 'dev';
} catch (e) { /* no git -> dev */ }
fs.writeFileSync(out, `// Generated by tools/write_version.js - stamped with the git commit hash by the build.\nexport const VERSION = '${v}';\n`);
console.log('version:', v, '->', out);
